// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NC_AdvinhaNum.Models;

#nullable disable

namespace NC_AdvinhaNum.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20240418214436_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("NC_AdvinhaNum.Models.AdvinhaNumerocs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("COD_JOGADOR")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataFormatada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HorarioTentativa")
                        .HasColumnType("TEXT");

                    b.Property<int>("NUM_TENTATIVA")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Porcentagem")
                        .HasColumnType("REAL");

                    b.Property<string>("Resultado")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdvinhaNC");
                });
#pragma warning restore 612, 618
        }
    }
}
